services:
  frontend:
    build: 
      context: ./client
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: 
      context: ./server
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
    restart: always
    