sonar.projectKey=software-design-202101536-kangyongseok_software-design-202101536-kangyongseok
sonar.organization=software-design-202101536-kangyongseok


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=software-design-202101536-kangyongseok
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=client/src,server

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Test paths
sonar.tests=client/src/__tests__,server/__tests__

# Coverage paths
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info

# Exclusions for code analysis
sonar.exclusions=**/node_modules/**,**/__tests__/**,**/dist/**,**/build/**,**/coverage/**

# Exclusions for coverage analysis
sonar.coverage.exclusions=**/node_modules/**,**/__tests__/**,**/tests/**,**/dist/**,**/build/**,**/coverage/**

# Exclusions for duplicate code detection
sonar.cpd.exclusions=**/node_modules/**,**/__tests__/**,**/tests/**,**/coverage/**