sonar.projectKey=software-design-202101536-kangyongseok_software-design-202101536-kangyongseok
sonar.organization=software-design-202101536-kangyongseok


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=software-design-202101536-kangyongseok
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8